In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("WineQT.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [52]:
df=pd.read_csv("WineQT.csv")
df[df['alcohol'] > 12]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
32,4.6,0.52,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.100000,4,45
91,5.6,0.50,0.09,2.3,0.049,17.0,99.0,0.99370,3.63,0.63,13.000000,5,131
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,142
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,144
148,9.7,0.53,0.60,2.0,0.039,5.0,19.0,0.99585,3.30,0.86,12.400000,6,210
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
1054,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,1477
1064,7.1,0.22,0.49,1.8,0.039,8.0,18.0,0.99344,3.39,0.56,12.400000,6,1490
1122,6.4,0.36,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.400000,6,1570
1125,6.0,0.58,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.500000,6,1573

In [53]:
df=pd.read_csv("WineQT.csv")
df[df['quality'] >= 7]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.00,7,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.50,7,8
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16
27,8.1,0.38,0.28,2.1,0.066,13.0,30.0,0.99680,3.23,0.73,9.70,7,37
89,8.0,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,6.6,0.56,0.14,2.4,0.064,13.0,29.0,0.99397,3.42,0.62,11.70,7,1534
1100,8.4,0.37,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.20,7,1544
1104,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.40,8,1549
1108,7.0,0.56,0.17,1.7,0.065,15.0,24.0,0.99514,3.44,0.68,10.55,7,1555
1133,6.7,0.32,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.60,7,1584

In [54]:
import pandas  as pd

In [55]:
df=pd.read_csv("WineQT.csv")
df[df['pH'] > 3.0]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [56]:
df=pd.read_csv("WineQT.csv")
df[(df['fixed acidity'] >= 8.0) & (df['fixed acidity'] <= 10.0)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
12,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
16,8.5,0.490,0.11,2.3,0.084,9.0,67.0,0.99680,3.17,0.53,9.4,5,23
23,8.3,0.655,0.12,2.3,0.083,15.0,113.0,0.99660,3.17,0.66,9.8,5,32
27,8.1,0.380,0.28,2.1,0.066,13.0,30.0,0.99680,3.23,0.73,9.7,7,37
29,8.8,0.610,0.30,2.8,0.088,17.0,46.0,0.99760,3.26,0.51,9.3,4,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058,8.2,0.280,0.60,3.0,0.104,10.0,22.0,0.99828,3.39,0.68,10.6,5,1481
1059,8.1,0.330,0.44,1.5,0.042,6.0,12.0,0.99542,3.35,0.61,10.7,5,1483
1095,8.0,0.390,0.30,1.9,0.074,32.0,84.0,0.99717,3.39,0.61,9.0,5,1533
1100,8.4,0.370,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.2,7,1544
1127,8.0,0.300,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6,1576

In [57]:
df=pd.read_csv("WineQT.csv")
df[df['residual sugar'] > 5.0]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
25,7.8,0.645,0.00,5.5,0.086,5.0,18.0,0.99860,3.40,0.55,9.6,6,35
28,7.3,0.450,0.36,5.9,0.074,12.0,87.0,0.99780,3.33,0.83,10.5,5,40
106,7.1,0.430,0.42,5.5,0.071,28.0,128.0,0.99730,3.42,0.71,10.5,5,155
107,7.1,0.430,0.42,5.5,0.070,29.0,129.0,0.99730,3.42,0.72,10.5,5,156
108,7.1,0.430,0.42,5.5,0.071,28.0,128.0,0.99730,3.42,0.71,10.5,5,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,9.9,0.500,0.50,13.8,0.205,48.0,82.0,1.00242,3.16,0.75,8.8,5,1474
1053,9.9,0.500,0.50,13.8,0.205,48.0,82.0,1.00242,3.16,0.75,8.8,5,1476
1055,7.1,0.875,0.05,5.7,0.082,3.0,14.0,0.99808,3.40,0.52,10.2,3,1478
1111,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5,1558
1128,6.2,0.700,0.15,5.1,0.076,13.0,27.0,0.99622,3.54,0.60,11.9,6,1577

In [58]:
df=pd.read_csv("WineQT.csv")
df[df['chlorides'] == 0.075]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,5
85,7.3,0.695,0.00,2.5,0.075,3.0,13.0,0.99800,3.49,0.52,9.2,5,122
170,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.2,7,243
171,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.2,7,244
173,7.1,0.680,0.07,1.9,0.075,16.0,51.0,0.99685,3.38,0.52,9.5,5,246
180,9.4,0.340,0.37,2.2,0.075,5.0,13.0,0.99800,3.22,0.62,9.2,5,256
181,6.6,0.695,0.00,2.1,0.075,12.0,56.0,0.99680,3.49,0.67,9.2,5,257
281,7.7,0.690,0.05,2.7,0.075,15.0,27.0,0.99740,3.26,0.61,9.1,5,404
337,10.4,0.240,0.49,1.8,0.075,6.0,20.0,0.99770,3.18,1.06,11.0,6,477
359,10.4,0.240,0.46,1.8,0.075,6.0,21.0,0.99760,3.25,1.02,10.8,7,506
388,14.3,0.310,0.74,1.8,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,6,544
401,12.7,0.600,0.49,2.8,0.075,5.0,19.0,0.99940,3.14,0.57,11.4,5,560
405,12.7,0.600,0.49,2.8,0.075,5.0,19.0,0.99940,3.14,0.57,11.4,5,565
410,10.2,0.240,0.49,2.4,0.075,10.0,28.0,0.99780,3.14,0.61,10.4,5,572
431,6.3,0.360,0.19,3.2,0.075,15.0,39.0,0.99560,3.56,0.52,12.7,6,609
524,7.7,0.560,0.20,2.0,0.075,9.0,39.0,0.99870,3.48,0.62,9.3,5,734
528,8.3,0.760,0.29,4.2,0.075,12.0,16.0,0.99650,3.45,0.68,11.5,6,740
544,9.0,0.580,0.25,2.8,0.075,9.0,104.0,0.99779,3.23,0.57,9.7,5,760
599,10.1,0.310,0.35,1.6,0.075,9.0,28.0,0.99672,3.24,0.83,11.2,7,838
669,8.9,0.120,0.45,1.8,0.075,10.0,21.0,0.99552,3.41,0.76,11.9,7,949
670,8.9,0.120,0.45,1.8,0.075,10.0,21.0,0.99552,3.41,0.76,11.9,7,950
749,10.2,0.290,0.65,2.4,0.075,6.0,17.0,0.99565,3.22,0.63,11.8,6,1063
799,7.4,0.360,0.34,1.8,0.075,18.0,38.0,0.99330,3.38,0.88,13.6,7,1132
822,8.5,0.320,0.42,2.3,0.075,12.0,19.0,0.99434,3.14,0.71,11.8,7,1162
839,8.8,0.955,0.05,1.8,0.075,5.0,19.0,0.99616,3.30,0.44,9.6,4,1189
869,7.6,0.430,0.29,2.1,0.075,19.0,66.0,0.99718,3.40,0.64,9.5,5,1229
872,7.6,0.430,0.29,2.1,0.075,19.0,66.0,0.99718,3.40,0.64,9.5,5,1232
903,8.0,0.715,0.22,2.3,0.075,13.0,81.0,0.99688,3.24,0.54,9.5,6,1275
906,8.0,0.715,0.22,2.3,0.075,13.0,81.0,0.99688,3.24,0.54,9.5,6,1278
945,8.4,0.390,0.10,1.7,0.075,6.0,25.0,0.99581,3.09,0.43,9.7,6,1332
1097,7.0,0.550,0.13,2.2,0.075,15.0,35.0,0.99590,3.36,0.59,9.7,6,1535
1125,6.0,0.580,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.5,6,1573
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [59]:
df[df['density']>0.998]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
14,7.6,0.390,0.31,2.3,0.082,23.0,71.0,0.99820,3.52,0.65,9.700000,5,21
25,7.8,0.645,0.00,5.5,0.086,5.0,18.0,0.99860,3.40,0.55,9.600000,6,35
51,8.8,0.410,0.64,2.2,0.093,9.0,42.0,0.99860,3.54,0.66,10.500000,5,76
79,10.1,0.310,0.44,2.3,0.080,22.0,46.0,0.99880,3.32,0.67,9.700000,6,113
103,9.2,0.520,1.00,3.4,0.610,32.0,69.0,0.99960,2.74,2.00,9.400000,4,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,8.2,0.280,0.60,3.0,0.104,10.0,22.0,0.99828,3.39,0.68,10.600000,5,1479
1058,8.2,0.280,0.60,3.0,0.104,10.0,22.0,0.99828,3.39,0.68,10.600000,5,1481
1077,7.1,0.270,0.60,2.1,0.074,17.0,25.0,0.99814,3.38,0.72,10.600000,6,1508
1081,6.9,0.840,0.21,4.1,0.074,16.0,65.0,0.99842,3.53,0.72,9.233333,6,1514
1082,6.9,0.840,0.21,4.1,0.074,16.0,65.0,0.99842,3.53,0.72,9.250000,6,1515

In [60]:
filtered_df = df[
    (df['alcohol'] < 9.5) & 
    (df['quality'] == 5)
]

In [61]:
first_50_rows=df.iloc[:50]
first_50_rows

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.90,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.60,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.30,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.90,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.90,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4
5,7.4,0.660,0.00,1.80,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,5
6,7.9,0.600,0.06,1.60,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,6
7,7.3,0.650,0.00,1.20,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,7
8,7.8,0.580,0.02,2.00,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,8
9,6.7,0.580,0.08,1.80,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5,10
10,5.6,0.615,0.00,1.60,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,5,12
11,7.8,0.610,0.29,1.60,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,5,13
12,8.5,0.280,0.56,1.80,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7,16
13,7.9,0.320,0.51,1.80,0.341,17.0,56.0,0.9969,3.04,1.08,9.2,6,19
14,7.6,0.390,0.31,2.30,0.082,23.0,71.0,0.9982,3.52,0.65,9.7,5,21
15,7.9,0.430,0.21,1.60,0.106,10.0,37.0,0.9966,3.17,0.91,9.5,5,22
16,8.5,0.490,0.11,2.30,0.084,9.0,67.0,0.9968,3.17,0.53,9.4,5,23
17,6.9,0.400,0.14,2.40,0.085,21.0,40.0,0.9968,3.43,0.63,9.7,6,24
18,6.3,0.390,0.16,1.40,0.080,11.0,23.0,0.9955,3.34,0.56,9.3,5,25
19,7.6,0.410,0.24,1.80,0.080,4.0,11.0,0.9962,3.28,0.59,9.5,5,26
20,7.1,0.710,0.00,1.90,0.080,14.0,35.0,0.9972,3.47,0.55,9.4,5,28
21,7.8,0.645,0.00,2.00,0.082,8.0,16.0,0.9964,3.38,0.59,9.8,6,29
22,6.7,0.675,0.07,2.40,0.089,17.0,82.0,0.9958,3.35,0.54,10.1,5,30
23,8.3,0.655,0.12,2.30,0.083,15.0,113.0,0.9966,3.17,0.66,9.8,5,32
24,5.2,0.320,0.25,1.80,0.103,13.0,50.0,0.9957,3.38,0.55,9.2,5,34
25,7.8,0.645,0.00,5.50,0.086,5.0,18.0,0.9986,3.40,0.55,9.6,6,35
26,7.8,0.600,0.14,2.40,0.086,3.0,15.0,0.9975,3.42,0.60,10.8,6,36
27,8.1,0.380,0.28,2.10,0.066,13.0,30.0,0.9968,3.23,0.73,9.7,7,37
28,7.3,0.450,0.36,5.90,0.074,12.0,87.0,0.9978,3.33,0.83,10.5,5,40
29,8.8,0.610,0.30,2.80,0.088,17.0,46.0,0.9976,3.26,0.51,9.3,4,41
30,7.5,0.490,0.20,2.60,0.332,8.0,14.0,0.9968,3.21,0.90,10.5,6,42
31,8.1,0.660,0.22,2.20,0.069,9.0,23.0,0.9968,3.30,1.20,10.3,5,43
32,4.6,0.520,0.15,2.10,0.054,8.0,65.0,0.9934,3.90,0.56,13.1,4,45
33,7.7,0.935,0.43,2.20,0.114,22.0,114.0,0.9970,3.25,0.73,9.2,5,46
34,8.8,0.660,0.26,1.70,0.074,4.0,23.0,0.9971,3.15,0.74,9.2,5,50
35,6.6,0.520,0.04,2.20,0.069,8.0,15.0,0.9956,3.40,0.63,9.4,6,51
36,6.6,0.500,0.04,2.10,0.068,6.0,14.0,0.9955,3.39,0.64,9.4,6,52
37,8.6,0.380,0.36,3.00,0.081,30.0,119.0,0.9970,3.20,0.56,9.4,5,53
38,7.6,0.510,0.15,2.80,0.110,33.0,73.0,0.9955,3.17,0.63,10.2,6,54
39,10.2,0.420,0.57,3.40,0.070,4.0,10.0,0.9971,3.04,0.63,9.6,5,56
40,7.8,0.590,0.18,2.30,0.076,17.0,54.0,0.9975,3.43,0.59,10.0,5,58
41,7.3,0.390,0.31,2.40,0.074,9.0,46.0,0.9962,3.41,0.54,9.4,6,59
42,8.8,0.400,0.40,2.20,0.079,19.0,52.0,0.9980,3.44,0.64,9.2,5,60
43,7.7,0.690,0.49,1.80,0.115,20.0,112.0,0.9968,3.21,0.71,9.3,5,61
44,7.0,0.735,0.05,2.00,0.081,13.0,54.0,0.9966,3.39,0.57,9.8,5,63
45,7.2,0.725,0.05,4.65,0.086,4.0,11.0,0.9962,3.41,0.39,10.9,5,64
46,7.2,0.725,0.05,4.65,0.086,4.0,11.0,0.9962,3.41,0.39,10.9,5,65
47,6.6,0.705,0.07,1.60,0.076,6.0,15.0,0.9962,3.44,0.58,10.7,5,67
48,8.0,0.705,0.05,1.90,0.074,8.0,19.0,0.9962,3.34,0.95,10.5,6,69
49,7.7,0.690,0.22,1.90,0.084,18.0,94.0,0.9961,3.31,0.48,9.5,5,72

In [62]:
extract_df = df[df['quality'] == 8][['pH', 'alcohol']]

In [63]:
df['volatile acidity'].max()

np.float64(1.58)

In [64]:
filtered_df = df[df['citric acid'] == 0]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.0,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.0,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
4,7.4,0.700,0.0,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
5,7.4,0.660,0.0,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,5
7,7.3,0.650,0.0,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,6.8,0.670,0.0,1.9,0.080,22.0,39.0,0.99701,3.40,0.74,9.7,5,1447
1035,6.5,0.900,0.0,1.6,0.052,9.0,17.0,0.99467,3.50,0.63,10.9,6,1455
1040,6.2,0.785,0.0,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0,4,1461
1105,7.1,0.670,0.0,2.3,0.083,18.0,27.0,0.99768,3.44,0.54,9.4,5,1551
1107,7.3,0.735,0.0,2.2,0.080,18.0,28.0,0.99765,3.41,0.60,9.4,5,1553

In [65]:
filtered_df = df[df['sulphates'] > 10]
filtered_df

Empty DataFrame
Columns: [fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality, Id]
Index: []

In [66]:
df['quality_label'] = df['quality'].transform(lambda x: 'Good' if x > 7 else 'Bad')
filtered_df = df[df['quality_label'] == 'Good']
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
190,7.9,0.35,0.46,3.6,0.078,15.0,37.0,0.99730,3.35,0.86,12.8,8,267,Good
197,10.3,0.32,0.45,6.4,0.073,5.0,13.0,0.99760,3.23,0.82,12.6,8,278,Good
271,5.6,0.85,0.05,1.4,0.045,12.0,88.0,0.99240,3.56,0.82,12.9,8,390,Good
310,12.6,0.31,0.72,2.2,0.072,6.0,29.0,0.99870,2.88,0.82,9.8,8,440,Good
321,11.3,0.62,0.67,5.2,0.086,6.0,19.0,0.99880,3.22,0.69,13.4,8,455,Good
340,9.4,0.30,0.56,2.8,0.080,6.0,17.0,0.99640,3.15,0.92,11.7,8,481,Good
349,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,495,Good
352,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,498,Good
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588,Good
747,9.1,0.40,0.50,1.8,0.071,7.0,16.0,0.99462,3.21,0.69,12.5,8,1061,Good
769,10.0,0.26,0.54,1.9,0.083,42.0,74.0,0.99451,2.98,0.63,11.8,8,1090,Good
793,7.9,0.54,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.1,8,1120,Good
850,8.6,0.42,0.39,1.8,0.068,6.0,12.0,0.99516,3.35,0.69,11.7,8,1202,Good
996,7.2,0.33,0.33,1.7,0.061,3.0,13.0,0.99600,3.23,1.10,10.0,8,1403,Good
1030,7.2,0.38,0.31,2.0,0.056,15.0,29.0,0.99472,3.23,0.76,11.3,8,1449,Good
1104,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8,1549,Good

In [67]:
filtered_df=df[df['total sulfur dioxide']>2*df['free sulfur dioxide']]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0,Bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1,Bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2,Bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3,Bad
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1125,6.0,0.580,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.5,6,1573,Bad
1128,6.2,0.700,0.15,5.1,0.076,13.0,27.0,0.99622,3.54,0.60,11.9,6,1577,Bad
1130,7.4,0.350,0.33,2.4,0.068,9.0,26.0,0.99470,3.36,0.60,11.9,6,1580,Bad
1131,6.1,0.715,0.10,2.6,0.053,13.0,27.0,0.99362,3.57,0.50,11.9,5,1582,Bad
1132,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5,1583,Bad

In [68]:
selected_row=df.iloc[100:201,:3]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0,Bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1,Bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2,Bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3,Bad
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1125,6.0,0.580,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.5,6,1573,Bad
1128,6.2,0.700,0.15,5.1,0.076,13.0,27.0,0.99622,3.54,0.60,11.9,6,1577,Bad
1130,7.4,0.350,0.33,2.4,0.068,9.0,26.0,0.99470,3.36,0.60,11.9,6,1580,Bad
1131,6.1,0.715,0.10,2.6,0.053,13.0,27.0,0.99362,3.57,0.50,11.9,5,1582,Bad
1132,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5,1583,Bad

In [69]:
filtered_df=df[df['alcohol']> df['alcohol'].mean()]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16,Bad
26,7.8,0.60,0.14,2.4,0.086,3.0,15.0,0.99750,3.42,0.60,10.8,6,36,Bad
28,7.3,0.45,0.36,5.9,0.074,12.0,87.0,0.99780,3.33,0.83,10.5,5,40,Bad
30,7.5,0.49,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5,6,42,Bad
32,4.6,0.52,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.1,4,45,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590,Bad
1137,5.4,0.74,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591,Bad
1138,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592,Bad
1140,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594,Bad
1141,5.9,0.55,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595,Bad

In [70]:
filtered_df = df[(df['fixed acidity'] > 12) | (df['volatile acidity'] > 1.0)]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
66,5.0,1.020,0.04,1.4,0.045,41.0,85.0,0.99380,3.75,0.48,10.5,4,94,Bad
83,7.3,1.070,0.09,1.7,0.178,10.0,89.0,0.99620,3.30,0.57,9.0,5,120,Bad
87,8.2,1.330,0.00,1.7,0.081,3.0,12.0,0.99640,3.53,0.49,10.9,5,126,Bad
88,8.1,1.330,0.00,1.8,0.082,3.0,12.0,0.99640,3.54,0.48,10.9,5,127,Bad
92,7.9,1.040,0.05,2.2,0.084,13.0,29.0,0.99590,3.22,0.55,9.9,6,134,Bad
142,6.9,1.090,0.06,2.1,0.061,12.0,31.0,0.99480,3.51,0.43,11.4,4,199,Bad
145,12.8,0.300,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.8,7,205,Bad
146,12.8,0.300,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.8,7,206,Bad
170,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.2,7,243,Bad
171,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.2,7,244,Bad
188,12.5,0.560,0.49,2.4,0.064,5.0,27.0,0.99990,3.08,0.87,10.9,5,264,Bad
211,13.3,0.340,0.52,3.2,0.094,17.0,53.0,1.00140,3.05,0.81,9.5,6,294,Bad
234,13.4,0.270,0.62,2.6,0.082,6.0,21.0,1.00020,3.16,0.67,9.7,6,328,Bad
240,12.5,0.280,0.54,2.3,0.082,12.0,29.0,0.99970,3.11,1.36,9.8,7,339,Bad
244,13.8,0.490,0.67,3.0,0.093,6.0,15.0,0.99860,3.02,0.93,12.0,6,347,Bad
248,13.5,0.530,0.79,4.8,0.120,23.0,77.0,1.00180,3.18,0.77,13.0,5,353,Bad
254,12.6,0.380,0.66,2.6,0.088,10.0,41.0,1.00100,3.17,0.68,9.8,6,359,Bad
258,12.5,0.460,0.63,2.0,0.071,6.0,15.0,0.99880,2.99,0.87,10.2,5,363,Bad
259,12.8,0.615,0.66,5.8,0.083,7.0,42.0,1.00220,3.07,0.73,10.0,7,364,Bad
260,12.8,0.615,0.66,5.8,0.083,7.0,42.0,1.00220,3.07,0.73,10.0,7,366,Bad
272,13.7,0.415,0.68,2.9,0.085,17.0,43.0,1.00140,3.06,0.80,10.0,6,391,Bad
279,12.2,0.480,0.54,2.6,0.085,19.0,64.0,1.00000,3.10,0.61,10.5,6,402,Bad
284,12.5,0.460,0.49,4.5,0.070,26.0,49.0,0.99810,3.05,0.57,9.6,4,409,Bad
301,12.8,0.840,0.63,2.4,0.088,13.0,35.0,0.99970,3.10,0.60,10.4,6,429,Bad
304,12.3,0.390,0.63,2.3,0.091,6.0,18.0,1.00040,3.16,0.49,9.5,5,433,Bad
306,12.3,0.390,0.63,2.3,0.091,6.0,18.0,1.00040,3.16,0.49,9.5,5,435,Bad
310,12.6,0.310,0.72,2.2,0.072,6.0,29.0,0.99870,2.88,0.82,9.8,8,440,Good
311,15.6,0.685,0.76,3.7,0.100,6.0,43.0,1.00320,2.95,0.68,11.2,7,442,Bad
313,12.5,0.380,0.60,2.6,0.081,31.0,72.0,0.99960,3.10,0.73,10.5,5,446,Bad
332,13.0,0.320,0.65,2.6,0.093,15.0,47.0,0.99960,3.05,0.61,10.6,5,470,Bad
334,12.5,0.370,0.55,2.6,0.083,25.0,68.0,0.99950,3.15,0.82,10.4,6,472,Bad
361,13.3,0.290,0.75,2.8,0.084,23.0,43.0,0.99860,3.04,0.68,11.4,7,509,Bad
367,12.5,0.600,0.49,4.3,0.100,5.0,14.0,1.00100,3.25,0.74,11.9,6,516,Bad
382,12.9,0.350,0.49,5.8,0.066,5.0,35.0,1.00140,3.20,0.66,12.0,7,538,Bad
388,14.3,0.310,0.74,1.8,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,6,544,Bad
392,12.4,0.350,0.49,2.6,0.079,27.0,69.0,0.99940,3.12,0.75,10.4,6,548,Bad
396,5.0,1.040,0.24,1.6,0.050,32.0,96.0,0.99340,3.74,0.62,11.5,5,553,Bad
397,15.5,0.645,0.49,4.2,0.095,10.0,23.0,1.00315,2.92,0.74,11.1,5,554,Bad
399,15.6,0.645,0.49,4.2,0.095,10.0,23.0,1.00315,2.92,0.74,11.1,5,557,Bad
400,13.0,0.470,0.49,4.3,0.085,6.0,47.0,1.00210,3.30,0.68,12.7,6,559,Bad
401,12.7,0.600,0.49,2.8,0.075,5.0,19.0,0.99940,3.14,0.57,11.4,5,560,Bad
404,13.0,0.470,0.49,4.3,0.085,6.0,47.0,1.00210,3.30,0.68,12.7,6,564,Bad
405,12.7,0.600,0.49,2.8,0.075,5.0,19.0,0.99940,3.14,0.57,11.4,5,565,Bad
415,12.3,0.500,0.49,2.2,0.089,5.0,14.0,1.00020,3.19,0.44,9.6,5,580,Bad
416,12.3,0.500,0.49,2.2,0.089,5.0,14.0,1.00020,3.19,0.44,9.6,5,581,Bad
425,12.4,0.400,0.51,2.0,0.059,6.0,24.0,0.99940,3.04,0.60,9.3,6,596,Bad
433,13.2,0.380,0.55,2.7,0.081,5.0,16.0,1.00060,2.98,0.54,9.4,5,611,Bad
462,15.9,0.360,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652,Bad
497,10.6,1.020,0.43,2.9,0.076,26.0,88.0,0.99840,3.08,0.57,10.1,6,700,Bad
502,8.4,1.035,0.15,6.0,0.073,11.0,54.0,0.99900,3.37,0.49,9.9,5,705,Bad
506,10.6,1.025,0.43,2.8,0.080,21.0,84.0,0.99850,3.06,0.57,10.1,5,710,Bad
584,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6,811,Bad
586,12.6,0.410,0.54,2.8,0.103,19.0,41.0,0.99939,3.21,0.76,11.3,6,814,Bad
710,7.7,1.005,0.15,2.1,0.102,11.0,32.0,0.99604,3.23,0.48,10.0,5,1012,Bad
864,12.6,0.390,0.49,2.5,0.080,8.0,20.0,0.99920,3.07,0.82,10.3,6,1224,Bad
891,6.3,1.020,0.00,2.0,0.083,17.0,24.0,0.99437,3.59,0.55,11.2,4,1261,Bad
922,7.6,1.580,0.00,2.1,0.137,5.0,9.0,0.99476,3.50,0.40,10.9,3,1299,Bad
931,8.0,1.180,0.21,1.9,0.083,14.0,41.0,0.99532,3.34,0.47,10.5,5,1312,Bad
1044,6.7,1.040,0.08,2.3,0.067,19.0,32.0,0.99648,3.52,0.57,11.0,4,1467,Bad

In [71]:
filtered_df = df[df['chlorides'] <= df['chlorides'].quantile(0.10)]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
32,4.6,0.520,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.1,4,45,Bad
66,5.0,1.020,0.04,1.4,0.045,41.0,85.0,0.99380,3.75,0.48,10.5,4,94,Bad
91,5.6,0.500,0.09,2.3,0.049,17.0,99.0,0.99370,3.63,0.63,13.0,5,131,Bad
96,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142,Bad
98,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1118,6.7,0.160,0.64,2.1,0.059,24.0,52.0,0.99494,3.34,0.71,11.2,6,1566,Bad
1121,6.2,0.510,0.14,1.9,0.056,15.0,34.0,0.99396,3.48,0.57,11.5,6,1569,Bad
1123,6.4,0.380,0.14,2.2,0.038,15.0,25.0,0.99514,3.44,0.65,11.1,6,1571,Bad
1126,7.5,0.520,0.40,2.2,0.060,12.0,20.0,0.99474,3.26,0.64,11.8,6,1575,Bad
1131,6.1,0.715,0.10,2.6,0.053,13.0,27.0,0.99362,3.57,0.50,11.9,5,1582,Bad

In [72]:
filtered_df = df[
    (df['pH'].between(3.2, 3.4)) & 
    (df['density'] < 0.995)
]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7,7,Bad
238,8.9,0.43,0.45,1.9,0.052,6.0,16.0,0.99480,3.35,0.70,12.5,6,336,Bad
249,6.1,0.21,0.40,1.4,0.066,40.5,165.0,0.99120,3.25,0.59,11.9,6,354,Bad
329,8.8,0.46,0.45,2.6,0.065,7.0,18.0,0.99470,3.32,0.79,14.0,6,467,Bad
580,8.4,0.25,0.39,2.0,0.041,4.0,10.0,0.99386,3.27,0.71,12.5,7,806,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1126,7.5,0.52,0.40,2.2,0.060,12.0,20.0,0.99474,3.26,0.64,11.8,6,1575,Bad
1130,7.4,0.35,0.33,2.4,0.068,9.0,26.0,0.99470,3.36,0.60,11.9,6,1580,Bad
1133,6.7,0.32,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,7,1584,Bad
1134,7.5,0.31,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4,6,1586,Bad
1136,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590,Bad

In [73]:
df[df['residual sugar']%2==0]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7,8,Bad
21,7.8,0.645,0.00,2.0,0.082,8.0,16.0,0.99640,3.38,0.59,9.8,6,29,Bad
44,7.0,0.735,0.05,2.0,0.081,13.0,54.0,0.99660,3.39,0.57,9.8,5,63,Bad
53,6.7,0.750,0.12,2.0,0.086,12.0,80.0,0.99580,3.38,0.52,10.1,5,78,Bad
56,7.4,0.500,0.47,2.0,0.086,21.0,73.0,0.99700,3.36,0.57,9.1,5,82,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,7.2,0.695,0.13,2.0,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5,1562,Bad
1116,7.2,0.695,0.13,2.0,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5,1563,Bad
1119,7.2,0.695,0.13,2.0,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5,1567,Bad
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594,Bad
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597,Bad

In [74]:
top_10_wines=df.nlargest(10,'alcohol')
top_10_wines

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
462,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652,Bad
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142,Bad
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144,Bad
329,8.8,0.46,0.45,2.6,0.065,7.0,18.0,0.99470,3.32,0.79,14.0,6,467,Bad
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588,Good
589,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,821,Bad
898,5.0,0.38,0.01,1.6,0.048,26.0,60.0,0.99084,3.70,0.75,14.0,6,1270,Bad
787,5.0,0.40,0.50,4.3,0.046,29.0,80.0,0.99020,3.49,0.66,13.6,6,1114,Bad
799,7.4,0.36,0.34,1.8,0.075,18.0,38.0,0.99330,3.38,0.88,13.6,7,1132,Bad
868,5.1,0.42,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.6,7,1228,Bad

In [75]:
filtered_df=df[
    (df['quality']!=5)|
    (df['quality']!=6)
    ]
filtered_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0,Bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1,Bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2,Bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3,Bad
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592,Bad
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593,Bad
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594,Bad
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595,Bad
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597,Bad

In [76]:
df[df["citric acid"]>df["volatile acidity"]]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_label
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3,Bad
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16,Bad
13,7.9,0.32,0.51,1.8,0.341,17.0,56.0,0.99690,3.04,1.08,9.2,6,19,Bad
39,10.2,0.42,0.57,3.4,0.070,4.0,10.0,0.99710,3.04,0.63,9.6,5,56,Bad
51,8.8,0.41,0.64,2.2,0.093,9.0,42.0,0.99860,3.54,0.66,10.5,5,76,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1118,6.7,0.16,0.64,2.1,0.059,24.0,52.0,0.99494,3.34,0.71,11.2,6,1566,Bad
1122,6.4,0.36,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.4,6,1570,Bad
1127,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6,1576,Bad
1133,6.7,0.32,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,7,1584,Bad
1134,7.5,0.31,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4,6,1586,Bad